/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
//IMPORTS
import backend.Producto;
import backend.Producto_Crud;
import com.mongodb.MongoException;
import javax.swing.*;
/**
 *
 * @author dell
 */
public class CrearProductoJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UsuariosJPanel
     */
    Producto_Crud crud;
    public CrearProductoJPanel(Producto_Crud crud) {
        this.crud = crud;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        container_content = new javax.swing.JPanel();
        content_header = new javax.swing.JPanel();
        content_title = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabelEdad = new javax.swing.JLabel();
        jButtonCrear = new javax.swing.JButton();
        jButtonRegresar = new javax.swing.JButton();
        jTextFieldStock = new javax.swing.JTextField();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jLabelEmail1 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabelEdad1 = new javax.swing.JLabel();

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(600, 400));

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(30, 33, 44));
        title.setText("Producto");

        description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description.setForeground(new java.awt.Color(51, 51, 51));
        description.setText("Este módulo crea los productos .");

        container_content.setBackground(new java.awt.Color(255, 255, 255));
        container_content.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(243, 244, 247), 2, true));

        content_title.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        content_title.setText("Registro de Producto");

        javax.swing.GroupLayout content_headerLayout = new javax.swing.GroupLayout(content_header);
        content_header.setLayout(content_headerLayout);
        content_headerLayout.setHorizontalGroup(
            content_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_headerLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(content_title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        content_headerLayout.setVerticalGroup(
            content_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_title)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabelNombre.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelNombre.setText("Producto:");

        jTextFieldNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jLabelApellido.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelApellido.setText("Precio");

        jTextFieldPrecio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jLabelEdad.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelEdad.setText("Stock");

        jButtonCrear.setBackground(new java.awt.Color(0, 123, 255));
        jButtonCrear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrear.setText("Crear ");
        jButtonCrear.setBorder(null);
        jButtonCrear.setBorderPainted(false);
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });

        jButtonRegresar.setBackground(new java.awt.Color(3, 206, 164));
        jButtonRegresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegresar.setText("Regresar");
        jButtonRegresar.setBorder(null);
        jButtonRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegresarActionPerformed(evt);
            }
        });

        jTextFieldStock.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jTextFieldDescripcion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jLabelEmail1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelEmail1.setText("Descripcion :");

        jTextFieldCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jLabelEdad1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelEdad1.setText("Codigo");

        javax.swing.GroupLayout container_contentLayout = new javax.swing.GroupLayout(container_content);
        container_content.setLayout(container_contentLayout);
        container_contentLayout.setHorizontalGroup(
            container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(container_contentLayout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(jButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(jButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(container_contentLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(container_contentLayout.createSequentialGroup()
                        .addComponent(jLabelEmail1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(container_contentLayout.createSequentialGroup()
                        .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldDescripcion)
                            .addGroup(container_contentLayout.createSequentialGroup()
                                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(container_contentLayout.createSequentialGroup()
                                        .addComponent(jLabelEdad1)
                                        .addGap(72, 72, 72))
                                    .addGroup(container_contentLayout.createSequentialGroup()
                                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                        .addGap(34, 34, 34)))
                                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelNombre))
                                .addGap(20, 20, Short.MAX_VALUE)
                                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(container_contentLayout.createSequentialGroup()
                                        .addComponent(jLabelApellido)
                                        .addGap(72, 72, 72)
                                        .addComponent(jLabelEdad))
                                    .addGroup(container_contentLayout.createSequentialGroup()
                                        .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(35, 35, 35)))
                        .addGap(65, 65, 65))))
        );
        container_contentLayout.setVerticalGroup(
            container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_contentLayout.createSequentialGroup()
                .addComponent(content_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelApellido)
                    .addComponent(jLabelEdad)
                    .addComponent(jLabelEdad1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabelEmail1)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(container_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(container_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(description)
                            .addComponent(title))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(container_content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
     try {
        // Validar que los campos no estén vacíos
        if (jTextFieldNombre.getText().isEmpty() || 
            jTextFieldPrecio.getText().isEmpty() || 
            jTextFieldStock.getText().isEmpty() || 
            jTextFieldDescripcion.getText().isEmpty()) {
            
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
        return; 
     }

        double precio = Double.parseDouble(jTextFieldPrecio.getText());
        int stock = Integer.parseInt(jTextFieldStock.getText());
        int codigo = Integer.parseInt(jTextFieldCodigo.getText());
        if (precio <= 0 || stock <= 0 || codigo <= 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese valores positivos para precio y stock", "Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }

    String nombre = jTextFieldNombre.getText();
    String descripcion = jTextFieldDescripcion.getText();

    Producto producto = new Producto(codigo,nombre, descripcion, precio, stock);
    
    crud.crearProductoDB(producto);
    
    JOptionPane.showMessageDialog(this, "Producto creado con éxito");

    // Limpia los campos después de crear el usuario (opcional)
    jTextFieldNombre.setText("");
    jTextFieldPrecio.setText("");
    jTextFieldStock.setText("");
    jTextFieldDescripcion.setText("");
    jTextFieldCodigo.setText("");
} catch (NumberFormatException e) {
    JOptionPane.showMessageDialog(this, "Por favor, ingrese valores numéricos válidos", "Error", JOptionPane.ERROR_MESSAGE);
    jTextFieldPrecio.setText("");
    jTextFieldStock.setText("");
} catch (MongoException e) {
    JOptionPane.showMessageDialog(this, "Error al insertar los Datos en la base de datos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegresarActionPerformed
     
    }//GEN-LAST:event_jButtonRegresarActionPerformed
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel container_content;
    private javax.swing.JPanel content_header;
    private javax.swing.JLabel content_title;
    private javax.swing.JLabel description;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonRegresar;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEdad1;
    private javax.swing.JLabel jLabelEmail1;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
