/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import backend.Producto;
import backend.Producto_Crud;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dell
 */
public class TiendaPanel extends javax.swing.JPanel {

    /**
     * Creates new form TiendaPanel
     */
    Producto_Crud crud;
    ArrayList<Producto> productosSeleccionados; 
    
    public TiendaPanel(Producto_Crud crud) {
        this.crud = crud;
        initComponents();
        cargarTodosLosProductos();
        jTableProductos.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                // Obtener la fila seleccionada
                int filaSeleccionada = jTableProductos.getSelectedRow();
                // Obtener el producto seleccionado en esa fila
                Producto productoSeleccionado = obtenerProductoDeFila(filaSeleccionada);
                // Agregar el producto seleccionado al ArrayList
                productosSeleccionados.add(productoSeleccionado);
                // Puedes imprimir el producto seleccionado para verificar
                System.out.println("Producto seleccionado: " + productoSeleccionado);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg4 = new javax.swing.JPanel();
        title4 = new javax.swing.JLabel();
        description4 = new javax.swing.JLabel();
        container_content4 = new javax.swing.JPanel();
        content_header4 = new javax.swing.JPanel();
        content_title4 = new javax.swing.JLabel();
        jLabelNombre3 = new javax.swing.JLabel();
        jTextFieldCriterioBusqueda = new javax.swing.JTextField();
        jButtonMostrar = new javax.swing.JButton();
        jComboBoxCriterio = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProductos = new javax.swing.JTable();
        jButtonAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCantidad = new javax.swing.JTextField();

        bg4.setBackground(new java.awt.Color(255, 255, 255));
        bg4.setPreferredSize(new java.awt.Dimension(600, 400));

        title4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title4.setForeground(new java.awt.Color(30, 33, 44));
        title4.setText("Tienda");

        description4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description4.setForeground(new java.awt.Color(51, 51, 51));
        description4.setText("Este módulo listara los productos .");

        container_content4.setBackground(new java.awt.Color(255, 255, 255));
        container_content4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(243, 244, 247), 2, true));

        content_title4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        content_title4.setText("Lista de Productos");

        javax.swing.GroupLayout content_header4Layout = new javax.swing.GroupLayout(content_header4);
        content_header4.setLayout(content_header4Layout);
        content_header4Layout.setHorizontalGroup(
            content_header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_header4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(content_title4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        content_header4Layout.setVerticalGroup(
            content_header4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(content_header4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content_title4)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabelNombre3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabelNombre3.setText("Buscar");

        jTextFieldCriterioBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        jButtonMostrar.setBackground(new java.awt.Color(3, 206, 164));
        jButtonMostrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMostrar.setText("Mostrar");
        jButtonMostrar.setBorder(null);
        jButtonMostrar.setFocusable(false);
        jButtonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarActionPerformed(evt);
            }
        });

        jComboBoxCriterio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre", "Descripcion", "Codigo", " " }));

        jTableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Producto", "Detalles", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTableProductos);

        jButtonAgregar.setBackground(new java.awt.Color(0, 123, 255));
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.setBorder(null);
        jButtonAgregar.setBorderPainted(false);
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Cantidad");

        jTextFieldCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 219, 221), 2));

        javax.swing.GroupLayout container_content4Layout = new javax.swing.GroupLayout(container_content4);
        container_content4.setLayout(container_content4Layout);
        container_content4Layout.setHorizontalGroup(
            container_content4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(content_header4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(container_content4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabelNombre3)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldCriterioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
            .addGroup(container_content4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(container_content4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        container_content4Layout.setVerticalGroup(
            container_content4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(container_content4Layout.createSequentialGroup()
                .addComponent(content_header4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(container_content4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre3)
                    .addComponent(jTextFieldCriterioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, container_content4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(container_content4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
        );

        javax.swing.GroupLayout bg4Layout = new javax.swing.GroupLayout(bg4);
        bg4.setLayout(bg4Layout);
        bg4Layout.setHorizontalGroup(
            bg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(bg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description4)
                    .addComponent(title4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container_content4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        bg4Layout.setVerticalGroup(
            bg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(title4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(container_content4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg4, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
    
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarActionPerformed
         // Obtener el criterio de búsqueda seleccionado
    String criterio = (String) jComboBoxCriterio.getSelectedItem();
    // Obtener el valor de búsqueda ingresado por el usuario
    String valor = jTextFieldCriterioBusqueda.getText();
    
    // Imprimir los parámetros de búsqueda en la consola
    System.out.println("Criterio de búsqueda: " + criterio);
    System.out.println("Valor de búsqueda: " + valor);
    
    // Realizar la búsqueda de productos usando el Producto_Crud
    List<Producto> listaProductos = crud.buscarProductos(criterio, valor);
    
    // Mostrar los resultados en la tabla
    mostrarProductosEnTabla(listaProductos);
    }//GEN-LAST:event_jButtonMostrarActionPerformed
    
    private void mostrarProductosEnTabla(List<Producto> listaProductos) {
    DefaultTableModel model = (DefaultTableModel) jTableProductos.getModel();
    // Limpiar la tabla antes de mostrar nuevos datos
    model.setRowCount(0);
    
    // Iterar sobre la lista de productos y agregarlos a la tabla
    for (Producto producto : listaProductos) {
        Object[] row = {producto.getCodigo(), producto.getNombre(), producto.getDescripcion(), producto.getPrecio()};
        model.addRow(row);
    }
    }
    
    private void cargarTodosLosProductos() {
        List<Producto> listaProductos = crud.buscarProductos("Todos", "");
        mostrarProductosEnTabla(listaProductos);
    }
    
    private Producto obtenerProductoDeFila(int fila) {
        DefaultTableModel model = (DefaultTableModel) jTableProductos.getModel();
        int codigo = (int) model.getValueAt(fila, 0);
        String nombre = (String) model.getValueAt(fila, 1);
        String descripcion = (String) model.getValueAt(fila, 2);
        double precio = (double) model.getValueAt(fila, 3);
        int stock = (int) model.getValueAt(fila, 4);
        return new Producto(codigo, nombre, descripcion, precio, stock);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JPanel bg1;
    private javax.swing.JPanel bg2;
    private javax.swing.JPanel bg3;
    private javax.swing.JPanel bg4;
    private javax.swing.JPanel container_content;
    private javax.swing.JPanel container_content1;
    private javax.swing.JPanel container_content2;
    private javax.swing.JPanel container_content3;
    private javax.swing.JPanel container_content4;
    private javax.swing.JPanel content_header;
    private javax.swing.JPanel content_header1;
    private javax.swing.JPanel content_header2;
    private javax.swing.JPanel content_header3;
    private javax.swing.JPanel content_header4;
    private javax.swing.JLabel content_title;
    private javax.swing.JLabel content_title1;
    private javax.swing.JLabel content_title2;
    private javax.swing.JLabel content_title3;
    private javax.swing.JLabel content_title4;
    private javax.swing.JLabel description;
    private javax.swing.JLabel description1;
    private javax.swing.JLabel description2;
    private javax.swing.JLabel description3;
    private javax.swing.JLabel description4;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonCrear1;
    private javax.swing.JButton jButtonCrear2;
    private javax.swing.JButton jButtonMostrar;
    private javax.swing.JComboBox<String> jComboBoxCriterio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelApellido1;
    private javax.swing.JLabel jLabelApellido2;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelEdad1;
    private javax.swing.JLabel jLabelEdad2;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    private javax.swing.JLabel jLabelNombre3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableProductos;
    private javax.swing.JTextField jTextFieldCantidad;
    private javax.swing.JTextField jTextFieldCriterioBusqueda;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombre1;
    private javax.swing.JTextField jTextFieldNombre2;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldPrecio1;
    private javax.swing.JTextField jTextFieldPrecio2;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    // End of variables declaration//GEN-END:variables
}
